chore: fix syntax

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -28,31 +28,31 @@ jobs:
 
       - name: Initaialize and Apply dotfiles
         run: |
-        export CI=true
-        chezmoi init --apply --source=$GITHUB_WORKSPACE
+          export CI=true
+          chezmoi init --apply --source=$GITHUB_WORKSPACE
 
       - name: Verify tools
         run: |
-        zsh --version
-        alacritty --version
-        git --version
-        gcc --version
+          zsh --version
+          alacritty --version
+          git --version
+          gcc --version
 
-        starship --version
+          starship --version
      
-        cargo --version
-        zellij --version
-        eza --version
-        bat --version
-        fd --version
-        rg --version
-        broot --version
-        zenith --version
-        silicon --version
+          cargo --version
+          zellij --version
+          eza --version
+          bat --version
+          fd --version
+          rg --version
+          broot --version
+          zenith --version
+          silicon --version
       
-        if fc-list :family | grep -i "HackGen Console NF"
-          echo "Font installed successfully"
-        else
-          echo "Font not found"
-          exit 1
-        fi
+          if fc-list :family | grep -i "HackGen Console NF"
+            echo "Font installed successfully"
+          else
+            echo "Font not found"
+            exit 1
+          fi
